# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_compound.ipynb.

# %% auto 0
__all__ = ['Compound', 'CompoundBuilder']

# %% ../nbs/01_compound.ipynb 4
import pandas as pd
import chemlib

from .core import *

# %% ../nbs/01_compound.ipynb 16
class Compound(chemlib.Compound):
    def __init__(self,
        formula: str # the chemical formula
    ):
        super().__init__(formula)
        self.name = None
        self.mass = None
        self.moles = None
        self.specific_heat = None
    
    @property
    def heat_capacity(self):
        pass
    
    def temperature(
        self,
        idx # the time step
    ): # time series for the changes in temperature
        pass
    
    def setName(self, name):
        self.name = name
        return self

    def setAmount(self, **kwargs):
        amounts = self.get_amounts(**kwargs)
        self.mass = amounts['grams']
        self.moles = amounts['moles']
        return self

# %% ../nbs/01_compound.ipynb 23
class CompoundBuilder():
    
    def __init__(self, formula):
        self.compound = Compound(formula)

    def setMass(self, **kwargs):
        pass
