# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['ureg', 'Q', 'Unit']

# %% ../nbs/00_core.ipynb 4
from dataclasses import dataclass

from fastcore.test import test_eq
import pint

# %% ../nbs/00_core.ipynb 6
@dataclass
class Unit:
    """
    Default Units
    """
    
    # SI Unit
    LENGTH = 'meter'
    MASS = 'kilogram'
    TIME = 'second'
    TEMPERATURE = 'kelvin'
    
    # Derived from SI Unit
    MOLE = 'moles'
    SPECIFIC_HEAT = 'joule / (kilogram kelvin)'

# %% ../nbs/00_core.ipynb 8
ureg = pint.UnitRegistry(system='SI')
Q = ureg.Quantity # quantity
