# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_energy.ipynb.

# %% auto 0
__all__ = ['Energy', 'Work', 'Heat']

# %% ../nbs/03_energy.ipynb 5
class Energy:
    
    def conservation_of_energy(
        self,
        initial_energy, # intial energy
        final_energy # final energy
    ):
        pass
    
    def conservation_of_mass(
        self,
        initial_mass, # initial_mass
        final_mass # final mass
    ):
        pass

# %% ../nbs/03_energy.ipynb 7
class Work:
    pass

# %% ../nbs/03_energy.ipynb 9
class Heat:
    pass
