# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_gas.ipynb.

# %% auto 0
__all__ = ['Pressure', 'Gas', 'GasLaw', 'UnitGas']

# %% ../nbs/06_gas.ipynb 4
import pandas as pd
import sympy as smp

from .core import *
from .compound import Compound

# %% ../nbs/06_gas.ipynb 5
class Pressure:
    def __init__(self):
        self.data = pd.Series([], name='Pressure over time', dtype=object)
    
    def setInitial(self, value):
        self.data[0] = value
        return self
    
    def append(
        self,
        value # the pressure
    ): # append the pressure value to the series
        self.data[self.data.size] = value
        return self

# %% ../nbs/06_gas.ipynb 9
class Gas(Compound):
    pass

# %% ../nbs/06_gas.ipynb 11
class GasLaw:
    
    def boyle_law(self):
        p1, v1, p2, v2 = smp.symbols('p_1 v_1 p_2 v_2')
        return smp.Eq(p1*v1, p2*v2)
    
    def charles_law(self):
        t1, v1, t2, v2 = smp.symbols('t_1 v_1 t_2 v_2')
        return smp.Eq(t1/v1, t2/v2)
    
    def avogadro_law(self):
        n1, v1, n2, v2 = smp.symbols('n_1 v_1 n_2 v_2')
        return smp.Eq(n1/v1, n2/v2)

# %% ../nbs/06_gas.ipynb 18
class UnitGas(Unit):
    
    PRESSURE = 'atm'
    TEMPERATURE = 'kelvin'
