# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_gas.ipynb.

# %% auto 0
__all__ = ['Gas', 'GasLaw', 'UnitGas']

# %% ../nbs/06_gas.ipynb 4
from .core import *
from .compound import Compound

# %% ../nbs/06_gas.ipynb 5
class Gas(Compound):
    
    # def __init__(self):
    #     pass

    @property
    def pressure(self):
        pass

# %% ../nbs/06_gas.ipynb 7
class GasLaw:
    
    def boylelaw(self):
        pass

# %% ../nbs/06_gas.ipynb 9
class UnitGas(Unit):
    
    PRESSURE = 'atm'
    TEMPERATURE = 'kelvin'
