# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_reaction.ipynb.

# %% auto 0
__all__ = ['Reaction']

# %% ../nbs/02_reaction.ipynb 3
import pandas as pd
from fastcore.test import test_eq
import chemlib

from .core import *
from .compound import *

# %% ../nbs/02_reaction.ipynb 6
class Reaction(chemlib.Reaction):
    def __init__(self,
        reactants: list, # list of reactants
        products: list # list of products
    ):
        super().__init__(reactants, products)
    
    def table(self):
        molecules = []
        for molecule in r2.reactants:
            molecules.append([molecule.name, molecule.formula, molecule.mass, molecule.moles, 0])
        
        return pd.DataFrame(data=molecules, columns=['Name', 'Formula', 'Mass', 'Mole', 'Specifc Heat'])
