# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_reaction.ipynb.

# %% auto 0
__all__ = ['Reaction']

# %% ../nbs/02_reaction.ipynb 4
import pandas as pd
from fastcore.test import test_eq
import chemlib
import pint

from .core import *
from .compound import *

# %% ../nbs/02_reaction.ipynb 6
class Reaction(chemlib.Reaction):
    def __init__(self,
        reactants: list, # list of reactants
        products: list # list of products
    ):
        super().__init__(reactants, products)
    
    def info(self):
        return pd.DataFrame(data=[[1, 1, 1, 1]], columns=['Initial mass', 'Final mass', 'Initial energy', 'Final Energy'])
    
    def table(self):
        molecules = []
        columns = ['Name', 'Formula', 'Mass', 'Mole', 'Specifc Heat', 'Heat Capacity']
        for molecule in r2.reactants:
            molecules.append([
                molecule.name, molecule.formula,
                molecule.mass, molecule.moles,
                molecule.specific_heat, molecule.heat_capacity])
        
        return pd.DataFrame(data=molecules, columns=columns)
