# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_thermochemistry.ipynb.

# %% auto 0
__all__ = ['ThermalReaction', 'CoffeCup', 'CoffeCupBuilder']

# %% ../nbs/05_thermochemistry.ipynb 4
import numpy as np

from .core import *
from .reaction import Reaction
from .compound import Compound

# %% ../nbs/05_thermochemistry.ipynb 13
class ThermalReaction(Reaction):
    
    def standard_enthalpy(self):
        
        if self.is_balanced == False:
            raise Exception("You need to balance the chemical equation!")
        
        products = self.products
        reactants = self.reactants
        
        # TODO: add Standard Thermodynamic Quantities

# %% ../nbs/05_thermochemistry.ipynb 30
class CoffeCup:
    def __init__(self, reactants, products=None):
        pass
    
    def heat_capacity(self):
        return specific_heat * mass
    
    def reaction_heat(self): # the final reaction heat for each reactant and product
        
        if heat_capacity:
            heat = heat_capacity * change_in_temperature

# %% ../nbs/05_thermochemistry.ipynb 35
class CoffeCupBuilder:
    def __init__(self):
        pass
    def addSolvent(self):
        pass
