# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_thermochemistry.ipynb.

# %% auto 0
__all__ = ['Thermochemistry', 'CoffeCup', 'CoffeCupBuilder']

# %% ../nbs/05_thermochemistry.ipynb 3
from .core import *
from .compound import Compound

# %% ../nbs/05_thermochemistry.ipynb 5
class Thermochemistry:
    pass

# %% ../nbs/05_thermochemistry.ipynb 7
class CoffeCup:
    def __init__(self, reactants, products=None):
        pass
    
    def heat_capacity(self):
        return specific_heat * mass
    
    def reaction_heat(self): # the final reaction heat for each reactant and product
        
        if heat_capacity:
            heat = heat_capacity * change_in_temperature

# %% ../nbs/05_thermochemistry.ipynb 12
class CoffeCupBuilder:
    def __init__(self):
        pass
    def addSolvent(self):
        pass
