# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_utils.ipynb.

# %% auto 0
__all__ = ['liter_to_mole']

# %% ../nbs/00_utils.ipynb 4
from .core import *
from fastcore.test import test_eq

# %% ../nbs/00_utils.ipynb 5
def liter_to_mole(liter):
    liter = liter.to('liter')
    return Q(liter.magnitude / 22.4, Unit.MOLE)
